{
  "formatVersion": "1.1",
  "component": {
    "group": "com.elevensight",
    "module": "android-sdk",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.0.0-beta05"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.0.0-beta05"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.0.0-alpha12"
          },
          "excludes": [
            {
              "group": "androidx.appcompat",
              "module": "appcompat"
            }
          ]
        },
        {
          "group": "com.loopj.android",
          "module": "android-async-http",
          "version": {
            "requires": "1.4.9"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "org.squirrelframework",
          "module": "squirrel-foundation",
          "version": {
            "requires": "0.3.8"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "javaassist",
              "module": "javassist"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "com.google.code.gson",
              "module": "gson"
            },
            {
              "group": "org.mvel",
              "module": "mvel2"
            },
            {
              "group": "log4j",
              "module": "log4j"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.github.tony19",
          "module": "logback-android-classic",
          "version": {
            "requires": "1.1.1-3"
          }
        },
        {
          "group": "com.github.tony19",
          "module": "logback-android-core",
          "version": {
            "requires": "1.1.1-3"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.8"
          }
        },
        {
          "group": "com.facebook.react",
          "module": "react-android",
          "version": {
            "requires": "0.75.4"
          }
        },
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-sdk-1.0.0.aar",
          "url": "android-sdk-1.0.0.aar",
          "size": 51508065,
          "sha512": "d9f378970cf1659e93bb8fa16087f756aa5041ba5377a7387a45f0696764841ae872f9ae4963ce72b73c130401a9f38cd9a34a50139cb3ff086c652697d73a24",
          "sha256": "aead481e52c4c7e78d4062179020404580b486bb87e30edb0889548691414e9e",
          "sha1": "fcbae93f1e6869922de336cd2686ae590bb0355a",
          "md5": "461edc3601a9e295c749cf41cf57567d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "io.github.vicmikhailau",
          "module": "MaskedEditText",
          "version": {
            "requires": "4.0.7"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer",
          "version": {
            "requires": "2.16.0"
          }
        },
        {
          "group": "org.jitsi.react",
          "module": "jitsi-meet-sdk",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.intuit.sdp",
          "module": "sdp-android",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.intuit.ssp",
          "module": "ssp-android",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.0.0-beta05"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.0.0-beta05"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.0.0-alpha12"
          },
          "excludes": [
            {
              "group": "androidx.appcompat",
              "module": "appcompat"
            }
          ]
        },
        {
          "group": "com.loopj.android",
          "module": "android-async-http",
          "version": {
            "requires": "1.4.9"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "org.squirrelframework",
          "module": "squirrel-foundation",
          "version": {
            "requires": "0.3.8"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "javaassist",
              "module": "javassist"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "com.google.code.gson",
              "module": "gson"
            },
            {
              "group": "org.mvel",
              "module": "mvel2"
            },
            {
              "group": "log4j",
              "module": "log4j"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.github.tony19",
          "module": "logback-android-classic",
          "version": {
            "requires": "1.1.1-3"
          }
        },
        {
          "group": "com.github.tony19",
          "module": "logback-android-core",
          "version": {
            "requires": "1.1.1-3"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.8"
          }
        },
        {
          "group": "com.facebook.react",
          "module": "react-android",
          "version": {
            "requires": "0.75.4"
          }
        },
        {
          "group": "com.squareup.retrofit",
          "module": "retrofit",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-sdk-1.0.0.aar",
          "url": "android-sdk-1.0.0.aar",
          "size": 51508065,
          "sha512": "d9f378970cf1659e93bb8fa16087f756aa5041ba5377a7387a45f0696764841ae872f9ae4963ce72b73c130401a9f38cd9a34a50139cb3ff086c652697d73a24",
          "sha256": "aead481e52c4c7e78d4062179020404580b486bb87e30edb0889548691414e9e",
          "sha1": "fcbae93f1e6869922de336cd2686ae590bb0355a",
          "md5": "461edc3601a9e295c749cf41cf57567d"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "android-sdk-1.0.0-sources.jar",
          "url": "android-sdk-1.0.0-sources.jar",
          "size": 539337,
          "sha512": "77b65819a783295bc971134e2fda1008cdf0a39fc1d35ff6f79bab5285424a2a179e4478497a10226fc9c1486fde8ea9efb2696bd13512e8ae2bdc1ff7d2480f",
          "sha256": "f6c61923be756ae2903decce5f9097b9cdd3ff669bbad0a1a7d08bef45d43db1",
          "sha1": "946e4c65c53a7e23a0e25c0eeea22de068213fb6",
          "md5": "886495e0b4b8b7ff6cf5d0ae3e2d7618"
        }
      ]
    }
  ]
}
